/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src.com.empresa.aprendefp;

import com.empresa.aprendefp.dominio.Estudiante;
import com.empresa.aprendefp.dominio.Perfil;
import javax.swing.GroupLayout.Alignment;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.imageio.ImageIO;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;

/**
 *
 * @author nes
 */
public class Perfil1 extends javax.swing.JFrame {

	//Se crea un elemento de tipo estudiante que contiene la informacion del perfil actual
	private Estudiante estudiante = new Estudiante();

    /**
     * Creates new form Perfil1
     */
	//Constructor de la clase y se le asigna valor a estudiante
    public Perfil1(Estudiante est) {
    	this.estudiante=est;
        initComponents();
    }
    
    public Perfil1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Usuario = new javax.swing.JLabel();
        Usuario.setForeground(Color.LIGHT_GRAY);
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setForeground(Color.GRAY);
        Matricula = new java.awt.Label();
        Matricula.setForeground(Color.LIGHT_GRAY);
        jLabel4 = new javax.swing.JLabel();
        jLabel4.setForeground(Color.GRAY);
        Nombre = new java.awt.Label();
        Nombre.setForeground(Color.LIGHT_GRAY);
        jLabel5 = new javax.swing.JLabel();
        jLabel5.setForeground(Color.GRAY);
        BtnSalir = new javax.swing.JButton();
        BtnTeoria = new javax.swing.JButton();
        BtnEjer = new javax.swing.JButton();
        BtnProgres = new javax.swing.JButton();
        jProgres = new javax.swing.JProgressBar();
        int temp= 4*((int)this.estudiante.getPerfil().getProgreso().getNumTutos()+(int)this.estudiante.getPerfil().getProgreso().getNumEjer());
        if(temp>=96) {
        	temp=100;
        }
        jProgres.setValue(temp);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(24, 24, 24));

        jPanel1.setBackground(new java.awt.Color(24, 24, 24));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(100, 100, 100));
        jLabel1.setText("Perfil de Usuario");

        Usuario.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        Usuario.setText(this.estudiante.getPerfil().getUsuario());

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel3.setText("Nombre:");

        Matricula.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Matricula.setText(this.estudiante.getMatricula());

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel4.setText("Mtricula:");

        Nombre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Nombre.setText(this.estudiante.getNombre());

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jLabel5.setText("Progreso:");

        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	BtnSalirActionPerformed(evt);
            }
        });

        BtnTeoria.setText("Teoria");
        BtnTeoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	BtnTeoriaActionPerformed(evt);
            }
        });

        BtnEjer.setText("Ejercicios");
        BtnEjer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	BtnEjerActionPerformed(evt);
            }
        });

        BtnProgres.setText("Progreso");
        BtnProgres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	BtnProgresActionPerformed(evt);
            }
        });
        
        try{
        	System.out.println("1");
        	byte[] bi = this.estudiante.getPerfil().getImagen();
        	System.out.println("2");
            BufferedImage image = null;
            System.out.println("3");
            InputStream in = new ByteArrayInputStream(bi);
            System.out.println("4");
            image = ImageIO.read(in);
            System.out.println("5");
            ImageIcon imgi = new ImageIcon(image.getScaledInstance(60, 60, 0));
            System.out.println("6");
            Imagen = new JLabel(imgi);

        }catch(Exception ex){
        	Imagen = new JLabel("");
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(25)
        					.addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 787, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addContainerGap(66, Short.MAX_VALUE)
        					.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 746, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(139)
        					.addComponent(BtnSalir, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE)
        					.addGap(84)
        					.addComponent(BtnTeoria, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE)
        					.addGap(96)
        					.addComponent(BtnEjer, GroupLayout.PREFERRED_SIZE, 109, GroupLayout.PREFERRED_SIZE)
        					.addGap(52)
        					.addComponent(BtnProgres))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(224)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jProgres, GroupLayout.PREFERRED_SIZE, 412, GroupLayout.PREFERRED_SIZE)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addGap(43)
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(Usuario, GroupLayout.PREFERRED_SIZE, 175, GroupLayout.PREFERRED_SIZE)
        								.addGroup(jPanel1Layout.createSequentialGroup()
        									.addGap(17)
        									.addComponent(Imagen, GroupLayout.PREFERRED_SIZE, 108, GroupLayout.PREFERRED_SIZE)
        									.addPreferredGap(ComponentPlacement.UNRELATED)
        									.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        										.addComponent(jLabel3)
        										.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 89, GroupLayout.PREFERRED_SIZE)
        										.addComponent(Matricula, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
        										.addComponent(Nombre, GroupLayout.PREFERRED_SIZE, 306, GroupLayout.PREFERRED_SIZE)))))
        						.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE))))
        			.addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(27)
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(83)
        			.addComponent(Usuario, GroupLayout.PREFERRED_SIZE, 34, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(Imagen, GroupLayout.PREFERRED_SIZE, 74, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap())
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(jLabel3)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addComponent(Nombre, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(jLabel4)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(Matricula, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addGap(107)
        							.addComponent(jLabel5)))
        					.addGap(18)
        					.addComponent(jProgres, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(BtnSalir, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE)
        						.addComponent(BtnTeoria, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE)
        						.addComponent(BtnEjer, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE)
        						.addComponent(BtnProgres, GroupLayout.PREFERRED_SIZE, 36, GroupLayout.PREFERRED_SIZE))
        					.addGap(67))))
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    	//Boton que sale de la aplicacion
    	dispose();
    	prueba1 Iniciar = new prueba1();
    	Iniciar.setVisible(true);
    }//GEN-LAST:event_UsuarioActionPerformed
    
    private void BtnTeoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    	//se cierra la ventana actual y pasamos al temario.
        dispose();
        Temario temas = new Temario(this.estudiante);
        temas.setVisible(true);
    }//GEN-LAST:event_UsuarioActionPerformed
    
    private void BtnEjerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    	//se cierra la ventana actual y pasamos a la ventana de lista de ejercicios.
        dispose();
        temasEjer ejercicios = new temasEjer(this.estudiante);
        ejercicios.setVisible(true);
    }//GEN-LAST:event_UsuarioActionPerformed
    
    private void BtnProgresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    	//se cierra la ventana actual y pasamos a la ventana de Progreso.
    	dispose();
    	Progreso1 ejercicios = new Progreso1(this.estudiante);
        ejercicios.setVisible(true);
    }//GEN-LAST:event_UsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perfil1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEjer;
    private javax.swing.JButton BtnProgres;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton BtnTeoria;
    private java.awt.Label Matricula;
    private java.awt.Label Nombre;
    private javax.swing.JLabel Usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgres;
    private javax.swing.JSeparator jSeparator1;
    private JLabel Imagen;
    // End of variables declaration//GEN-END:variables
}
