/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src.com.empresa.aprendefp;

import javax.swing.JList;

import com.empresa.aprendefp.dominio.Estudiante;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;

/**
 *
 * @author Hilario
 */
public class tema2 extends javax.swing.JFrame {
	
	//Se crea un elemento de tipo estudiante que contiene la informacion del perfil actual
	private Estudiante estudiante = new Estudiante();
    /**
     * Creates new form Metodologia
     */
	//Constructor de la clase y se le asigna valor a estudiante
	public tema2(Estudiante est) {
		this.estudiante=est;
        initComponents();
    }
	
    public tema2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        SubTem1 = new javax.swing.JButton();
        SubTem2 = new javax.swing.JButton();
        SubTem3 = new javax.swing.JButton();
        SubTem4 = new javax.swing.JButton();
        SubTem5 = new javax.swing.JButton();
        SubTem6 = new javax.swing.JButton();
        SubTem7 = new javax.swing.JButton();
        SubTem8 = new javax.swing.JButton();
        SubTem9 = new javax.swing.JButton();
        SubTem10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(24, 24, 24));
        jPanel1.setPreferredSize(new java.awt.Dimension(899, 632));

        jPanel2.setDoubleBuffered(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Algoritmos y pseudocodigos");

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton4.setText("Perfil");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton5.setText("Salir");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        SubTem1.setFont(new Font("Dialog", Font.PLAIN, 18)); // NOI18N
        SubTem1.setText("Tipos de datos");
        SubTem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubTem1ActionPerformed(evt);
            }
        });

        SubTem2.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        SubTem2.setText("Definicion de variables 1");
      //El boton es bloqueado hasta que el usuario cumple los requisitos
        if(this.estudiante.getPerfil().getProgreso().getNumTutos()<9) {
        	SubTem2.setEnabled(false);
        }
        else {
        	SubTem2.setEnabled(true);
        }
        SubTem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubTem2ActionPerformed(evt);
            }
        });

        SubTem3.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        SubTem3.setText("Definicion de variables 2");
      //El boton es bloqueado hasta que el usuario cumple los requisitos
        if(this.estudiante.getPerfil().getProgreso().getNumTutos()<10) {
        	SubTem3.setEnabled(false);
        }
        else {
        	SubTem3.setEnabled(true);
        }
        SubTem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubTem3ActionPerformed(evt);
            }
        });

        SubTem4.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        SubTem4.setText("Definicion de variables 3");
      //El boton es bloqueado hasta que el usuario cumple los requisitos
        if(this.estudiante.getPerfil().getProgreso().getNumTutos()<11) {
        	SubTem4.setEnabled(false);
        }
        else {
        	SubTem4.setEnabled(true);
        }
        SubTem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubTem4ActionPerformed(evt);
            }
        });

        SubTem5.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        SubTem5.setText("Definicion de variables 4");
      //El boton es bloqueado hasta que el usuario cumple los requisitos
        if(this.estudiante.getPerfil().getProgreso().getNumTutos()<12) {
        	SubTem5.setEnabled(false);
        }
        else {
        	SubTem5.setEnabled(true);
        }
        SubTem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubTem5ActionPerformed(evt);
            }
        });

        SubTem6.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        SubTem6.setText("Condicionales");
      //El boton es bloqueado hasta que el usuario cumple los requisitos
        if(this.estudiante.getPerfil().getProgreso().getNumTutos()<13) {
        	SubTem6.setEnabled(false);
        }
        else {
        	SubTem6.setEnabled(true);
        }
        SubTem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubTem6ActionPerformed(evt);
            }
        });

        SubTem7.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        SubTem7.setText("Selectivas");
      //El boton es bloqueado hasta que el usuario cumple los requisitos
        if(this.estudiante.getPerfil().getProgreso().getNumTutos()<14) {
        	SubTem7.setEnabled(false);
        }
        else {
        	SubTem7.setEnabled(true);
        }
        SubTem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubTem7ActionPerformed(evt);
            }
        });

        SubTem8.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        SubTem8.setText("Repetitivas Mientras");
      //El boton es bloqueado hasta que el usuario cumple los requisitos
        if(this.estudiante.getPerfil().getProgreso().getNumTutos()<15) {
        	SubTem8.setEnabled(false);
        }
        else {
        	SubTem8.setEnabled(true);
        }
        SubTem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubTem8ActionPerformed(evt);
            }
        });

        SubTem9.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        SubTem9.setText("Selectivas");
      //El boton es bloqueado hasta que el usuario cumple los requisitos
        if(this.estudiante.getPerfil().getProgreso().getNumTutos()<16) {
        	SubTem9.setEnabled(false);
        }
        else {
        	SubTem9.setEnabled(true);
        }
        SubTem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubTem9ActionPerformed(evt);
            }
        });

        SubTem10.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        SubTem10.setText("Repetitivas Repetir");
      //El boton es bloqueado hasta que el usuario cumple los requisitos
        if(this.estudiante.getPerfil().getProgreso().getNumTutos()<17) {
        	SubTem10.setEnabled(false);
        }
        else {
        	SubTem10.setEnabled(true);
        }
        SubTem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubTem10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGap(171)
        			.addComponent(jButton5, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
        			.addGap(101)
        			.addComponent(jButton4, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jLabel6)
        			.addPreferredGap(ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(filler2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(filler1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(filler3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addGap(29)
        					.addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 730, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addGap(182)
        					.addComponent(jLabel1))
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addGap(227)
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(SubTem1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(SubTem2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(SubTem3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(SubTem5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(SubTem6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(SubTem7, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(SubTem4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(SubTem9, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(SubTem10, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(SubTem8, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        			.addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGap(6)
        			.addComponent(jLabel1)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 6, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(SubTem1)
        					.addGap(10)
        					.addComponent(SubTem2)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(SubTem3)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(SubTem4)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(SubTem5)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(SubTem6)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(SubTem7)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(SubTem8)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(SubTem10)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(SubTem9)
        					.addPreferredGap(ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(jPanel2Layout.createSequentialGroup()
        							.addComponent(jLabel6)
        							.addGap(44)
        							.addComponent(filler3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        						.addGroup(jPanel2Layout.createSequentialGroup()
        							.addComponent(filler1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addGap(32))
        						.addGroup(jPanel2Layout.createSequentialGroup()
        							.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        								.addComponent(jButton5, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE)
        								.addComponent(jButton4, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE))
        							.addContainerGap())))
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addGap(0, 472, Short.MAX_VALUE)
        					.addComponent(filler2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
        );
        jPanel2.setLayout(jPanel2Layout);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    	//boton que cierra la ventana actual crea un elemento de tipo Perfil1.
        dispose();
        Perfil1 perfil = new Perfil1(this.estudiante);
        perfil.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    	//Boton que sale de la aplicacion
    	dispose();
    	prueba1 Iniciar = new prueba1();
    	Iniciar.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    //boton Analisis de los datos
    private void SubTem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubTem2ActionPerformed
        // TODO add your handling code here:
    	//boton que cierra la ventana actual crea un elemento de tipo Tutoriales
    	dispose();
        Tutoriales tutoriales = new Tutoriales(2,2,this.estudiante);
        tutoriales.setVisible(true);
    }//GEN-LAST:event_SubTem2ActionPerformed

    //boton Definicion del problema
    private void SubTem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubTem1ActionPerformed
        // TODO add your handling code here:
    	//boton que cierra la ventana actual crea un elemento de tipo Tutoriales
    	dispose();
        Tutoriales tutoriales = new Tutoriales(2,1,this.estudiante);
        tutoriales.setVisible(true);
    }//GEN-LAST:event_SubTem1ActionPerformed

    //boton Diseño de la solucion
    private void SubTem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubTem3ActionPerformed
        // TODO add your handling code here:}
    	//boton que cierra la ventana actual crea un elemento de tipo Tutoriales
    	dispose();
        Tutoriales tutoriales = new Tutoriales(2,3,this.estudiante);
        tutoriales.setVisible(true);
    }//GEN-LAST:event_SubTem3ActionPerformed

    //boton Codificacion
    private void SubTem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubTem4ActionPerformed
        // TODO add your handling code here:
    	//boton que cierra la ventana actual crea un elemento de tipo Tutoriales
    	dispose();
        Tutoriales tutoriales = new Tutoriales(2,4,this.estudiante);
        tutoriales.setVisible(true);
    }//GEN-LAST:event_SubTem4ActionPerformed

    //boto Prueba y depuracion
    private void SubTem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubTem5ActionPerformed
        // TODO add your handling code here:
    	//boton que cierra la ventana actual crea un elemento de tipo Tutoriales
    	dispose();
        Tutoriales tutoriales = new Tutoriales(2,5,this.estudiante);
        tutoriales.setVisible(true);
    }//GEN-LAST:event_SubTem5ActionPerformed

    //boton Documentacion
    private void SubTem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubTem6ActionPerformed
        // TODO add your handling code here:
    	//boton que cierra la ventana actual crea un elemento de tipo Tutoriales
    	dispose();
        Tutoriales tutoriales = new Tutoriales(2,6,this.estudiante);
        tutoriales.setVisible(true);
    }//GEN-LAST:event_SubTem6ActionPerformed

    //boton Mantenimiento
    private void SubTem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubTem7ActionPerformed
        // TODO add your handling code here:
    	//boton que cierra la ventana actual crea un elemento de tipo Tutoriales
    	dispose();
        Tutoriales tutoriales = new Tutoriales(2,7,this.estudiante);
        tutoriales.setVisible(true);
    }//GEN-LAST:event_SubTem7ActionPerformed

    private void SubTem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubTem8ActionPerformed
        // TODO add your handling code here:
    	//boton que cierra la ventana actual crea un elemento de tipo Tutoriales
    	dispose();
        Tutoriales tutoriales = new Tutoriales(2,8,this.estudiante);
        tutoriales.setVisible(true);
    }//GEN-LAST:event_SubTem8ActionPerformed

    private void SubTem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubTem9ActionPerformed
        // TODO add your handling code here:
    	//boton que cierra la ventana actual crea un elemento de tipo Tutoriales
    	dispose();
        Tutoriales tutoriales = new Tutoriales(2,9,this.estudiante);
        tutoriales.setVisible(true);
    }//GEN-LAST:event_SubTem9ActionPerformed

    private void SubTem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubTem10ActionPerformed
        // TODO add your handling code here:
    	//boton que cierra la ventana actual crea un elemento de tipo Tutoriales
    	dispose();
        Tutoriales tutoriales = new Tutoriales(2,10,this.estudiante);
        tutoriales.setVisible(true);
    }//GEN-LAST:event_SubTem10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tema2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tema2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tema2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tema2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tema2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SubTem1;
    private javax.swing.JButton SubTem10;
    private javax.swing.JButton SubTem2;
    private javax.swing.JButton SubTem3;
    private javax.swing.JButton SubTem4;
    private javax.swing.JButton SubTem5;
    private javax.swing.JButton SubTem6;
    private javax.swing.JButton SubTem7;
    private javax.swing.JButton SubTem8;
    private javax.swing.JButton SubTem9;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
